# Generated by Django 3.2.9 on 2021-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=255, null=True)),
                ('Contraseña', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
